import Head from 'next/head'
import Auth from './auth/auth'

export default function Home() {

  return (
    <>
      <Head>
        <title>Piggy Bank App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{background: "#FFD0F5", height: "100%"}}>
        <Auth />
      </main>
    </>
  )
}
